### ISSUE TITLE
Function signature is a bit confusing to me

### ISSUE THREAD

**Issue by mstade** [websdk/vanilla#1]
As far as I can tell, the node isn't an optional argument – nor do I think it could be – so why isn't it a required argument to the component function? The spec says components should be ergonomic – a cool word to use, and I like it, but it's not defined what you mean by this. If you mean conventional, then surely `component(node, data)` is more "ergonomic" than `component.call(node, data)`. The `this` keyword in javascript is weird – intentions were good, but in reality it's more confusing than just having a "target" argument to the function.

Additionally, it seems to me some components may not be data driven at all, but rather entirely node driver (adding support for additional form methods for instance) making the `this` even weirder:

``` javascript
put.call(form)
```

Wat? Why not just `put(form)`? It strikes me as odd.

**Comment by pemrouz** [comment]
These are two very good points. We only use `this` in the same manner as a normal argument (no magic), so it's not any more complicated, but I agree the invocation looks slightly weirder than if we didn't.  

Some downsides I can think of - both fairly conventional reasons:
- We lose the out-of-the-box compatibility with D3:
  
  ``` js
  component.call(node)
  
  d3.select(node)
    .call(component)
  ```
  
  Although [this discussion on D3 4.0](https://github.com/d3/d3-selection/issues/43) shows that might change too anyway, because arrow functions. I think it's rare to need to write components using arrow functions (other than in demos), but that is something we will benefit from too if we change the signature. 
  
  However, we couldn't keep in sync with D3 4.0 if that is the case anyway, since we would need to put the node as the third argument, in an array to be accessed via the second parameter, which would be way too complicated. Since it's mandatory and having data isn't, it would need to be the first argument as you suggested.
- We would lose harmony with other functions, like event handlers, accessors and other utility functions. It's very useful to know that across all functions, `this` is the element (or more generally the "thing") I am operating on and the first argument is the data:
  
  ``` js
  once(node)('li', function(data){ /* this and data */ })
  selection.classed('foo', function(data){ /* this and data */ })
  o.on('event', function(data){ /* this and data */ })
  child.on('change', function(data){ /* this and data */ })
  ```
  
  We would have to change all these too, since I think there is huge benefit to having a single paradigm and eliminating the cognitive overhead of having to recall signatures for individual API. Obviously somethings like D3 we can't change, and coupled with the fact that this convention is the most commonplace, this would not be an easy change..

**Comment by pemrouz** [comment]
Correction: D3 will still set the `this` argument, `nodes` will be an additional way to access it, so the current signature will be compatible with D3 4.0.

**Comment by mstade** [comment]
I'd be very careful to base an API standard on the follies of one particular library, particularly when it can be easily "fixed" in the case you mentioned, and the general case is just your typical function call:

``` javascript
component(node)

d3.select(node)
  .call(component.bind(null, node))
```

It's less convenient in the more general case, where you don't know the node from context, but I'd rather recommend a generic d3 compatibility layer:

``` javascript
function d3compat(component) {
  return function(... args) {
    component(this, ... args)
  }
}

d3.select(node)
  .call(d3compat(component))
```

`this` is the very antithesis to consistency, and the fact that arrow functions in ES2015 treats them differently is even further evidence on that pile. Just as d3 can be "fixed," so can event handlers.

I'll have more reasoned commentary for you in a few hours, right now my flight is about to take off!

**Comment by pemrouz** [comment]
True. I don't have a very strong opinion on this, but would lean towards your suggestion. Best to take the refactor hit now and sort out the inconsistency with arrow functions rather than later on. Anyone else have any thoughts on this? //cc @sammyt @gabrielmontagne @mamapitufo

PS. @mstade, what do you think about setting up some sort of "discussions" team under @websdk to be able to tag people in for discussions?

PPS. Enjoy your trip, wherever you are off to! :)

**Comment by gabrielmontagne** [comment]
Hi, that makes sense. But at the risk of sounding old-school, I _do_ think that the node _should_ be the `this`.  
My thinking is that a component is a function _on data_ that you call _on a node_.
Or, `component.call(node, data)`.

Otherwise it becomes less clear and transportable what the arguments of the function are.

I know we could say the node should always be the first argument---a bit like the `self` in python---but then why, one might ask, can I not do `component(data, node, maybeAnotherNode, somethingInBetween)`.  And the clarity of the structure of what a component is becomes blurrier.

It'd then be a matter of "convention" that the node is what comes first---in handlers, etc----, but it's then easier to sometimes not send it first, and then APIs start again to "loosen up", shift and proliferate.

And this makes our APIs noise, where everything starts with `(node, data)`  while the `this` would then revert to the dark hole nobody knows what it refers to.

The `this` in JS is mostly a shitty confusing thing---except in this case.

**Comment by gabrielmontagne** [comment]
to go back to the original example, if we know the `this` is the node, it becomes clear that when you see `put.call(form)` your component is being called on a form with no data, instead of `form` maybe being maybe the data from the form, etc.

what data is should be clear. otherwise one might start to get confused and send `component(something)`  where that something might look like `{ things: [1,2,3], red: true, target: node, root: anotherNodeWhoKnowsWhichIsWhich }` etc.

**Comment by pemrouz** [comment]
How about `(d, i, node)`? 

The original argument for `(d, i)` was to mimic the signature for array functions. This was also loosely the reasoning behind `(d, i, nodes)`. However, `(d, i, node)` is closer in that respect, since `d` is a property of `node`. Also, accessing other nodes from a component is a bit of an anti-pattern.

I've been experimenting with this in a few components, and although it's only a small change, it works pretty well and means arrow functions work for simpler components (example from [here](https://github.com/rijs/minimal)):

``` js
ripple('my-header', (d, i, el) => diff(el)`<h1>Hello ${d.name}</h1>`)
```

`this` can also still be set as the `node`.

**Comment by mamapitufo** [comment]
Going back to the original post: why is the node (the only required argument for a visual component) not the first argument? Following @pemrouz latest proposal, a component that requires no data would be applied like `foo(undefined, undefined, node)`...

**Comment by pemrouz** [comment]
^ Fair point :). I can't see any better solution than `component(node, data)`. 

I've opened to #2 that changes this. 

And also now moved this over to `websdk`, so feel free to change/merge as you please!

**Comment by gabrielmontagne** [comment]
we tried, and seemed to work quite nice, component({node, data}) Came from
@mstade, and worked much better for us for functional composition like
a(b(c({node, data}), if the functions themselsves return {node, data}. This
allows for data processing components  (fancy filters, sorters, etc) by
returning different data sets; of course node manipulation; but also
components that return different nodes -- by either sun selecting or
building new stuff, like a modal etc.

**Comment by pemrouz** [comment]
Ah, that's quite interesting :+1: 

I had been doing `a(node, data); b(node, data); c(node, data)` to progressively enhance, but `a(b(c({node, data})))` is definitely more powerful. That way we lose the ability to pick out and set defaults like `function component(node, { focused, options = [], etc })`, but that's a fairly small point since you can just do it on the next line and it's worth the composition benefit. 

I'm +1 on that. If you get some time this week, feel free to update or create a new PR. Otherwise I should be able to do it next weekend :).

**Comment by pemrouz** [comment]
This is merged now (+components and apps tested and updated) 🎉

I haven't played with `component({ node, data })` so don't know enough to be able to spec that. Initial thoughts are that you can probably do something similar with a wrapper on top, but spec'ing it for all components might complicate things for the common use case (i.e. (a) they _have_ to return a value and (b) parameters are slightly less usable). Open to discussion though if anyone feels that is a better standard! :)
